### PR TITLE
Support Rails 7.2

### PR DESCRIPTION
**Pull request by AlexMooney**
I doubt any changes to the gem need to be made to support Rails 7.2, given that the [Active Record changes](https://guides.rubyonrails.org/7_2_release_notes.html#active-record) don't remove anything that I found in this code base by grepping.

There are plenty of deprecations from 7.1 that are being removed, but the main branch CI logs are not available, so I couldn't see if any deprecation warnings were present.

### CODE REVIEW

**Comment by jcoleman** [comment]
Thanks @AlexMooney. I approved the CI run; will that give you the logs to verify deprecation warnings (or lack thereof)?

**Comment by AlexMooney** [comment]
> I approved the CI run; will that give you the logs to verify deprecation warnings (or lack thereof)?

Thanks, that would give the data on the deprecations but it looks like the ci is broken and not able to start Postgres containers.

**Comment by jcoleman** [comment]
@AlexMooney Huh, not having frequent commits leads to missing that I guess. I'll try to take a look tomorrow to try to get it running again.

**Comment by jcoleman** [comment]
@AlexMooney If you can rebase this branch I think CI should pass now.

**Comment by AlexMooney** [comment]
@jcoleman unfortunately it seems you have to approve the workflow with each change. I've just rebased the change onto your master branch CI fixes.

**Comment by AlexMooney** [comment]
I've looked at all of the RSpec runs in Rails 7.2 and don't see any deprecation messages or warnings of any kind.

**Review by jcoleman — APPROVED** [review]

**Comment by jcoleman** [comment]
@AlexMooney I'll try to release an updated gem either tonight or tomorrow.

**Comment by jcoleman** [comment]
Pushed 1.9.1.

**Pull request merged**
